
image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      cd ~ && curl -L https://storage.googleapis.com/julialang2/bin/linux/x64/$JULIA_MINOR_VERSION/julia-$JULIA_BUGFIX_VERSION-linux-x86_64.tar.gz 
      | tar -xzf - && mv julia-$JULIA_BUGFIX_VERSION julia
      && echo "PATH_add ~/julia/bin" > /workspace/.envrc 
      && echo 'export SEARCHLIGHT_USERNAME="gitpod"' >> /workspace/.envrc 
      && direnv allow /workspace
      && cd $GITPOD_REPO_ROOT
      && julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate();using NBInclude;@nbinclude("testAPI.ipynb")'
  - command: python3 -m http.server 8080 -d docs/build
  - command: gp preview $(gp url 8080)
