
image:
  file: .gitpod.Dockerfile
tasks:
  - before: >
      echo "PATH_add ~/julia/bin" > $GITPOD_REPO_ROOT/.envrc 
      && echo 'export SEARCHLIGHT_USERNAME="gitpod"' >> $$GITPOD_REPO_ROOT/.envrc 
      && direnv allow $$GITPOD_REPO_ROOT
      && cd $GITPOD_REPO_ROOT
  - init: >
      cd ~ && curl -L https://storage.googleapis.com/julialang2/bin/linux/x64/$JULIA_MINOR_VERSION/julia-$JULIA_BUGFIX_VERSION-linux-x86_64.tar.gz 
      | tar -xzf - && mv julia-$JULIA_BUGFIX_VERSION julia
  - command: ./makedoc.sh &
  - command: gp open testAPI.ipynb
